# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
baseURL: http://localhost:1313/
languageCode: en-us
title: marcusz's site
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: marcusz's site
  description: Tech Person
  keywords: ["Tech", "Blog", "Fun"]
  author: marcusz
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006" # https://gohugo.io/functions/format/
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true # Navigation (like address bars)
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js (hugo syntax highlighter)
    disableFingerprinting: true
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon16x16.ico"
    favicon32x32: "/icons/favicon.ico"
    apple_touch_icon: "/icons/apple-touch-icon.png" #180x180
    # safari_pinned_tab: "/icons/icon.png"

  label:
    text: "marcusz's site" # This is seen in the top left corner
    icon: "/icons/apple-touch-icon.png" # This is seen in the top left corner next to the title
    iconHeight: 35

  # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
  profileMode:
    enabled: false # disabling this will fallback to homeInfo mode
    title: marcusz's site
    subtitle: Tech person
    imageUrl: "/icons/icon.png"
    imageWidth: 150
    imageHeight: 150
    imageTitle: main
    buttons:
      - name: About Me
        url: "/about"
      - name: Tags
        url: "/tags"
      - name: Blogs
        url: "/posts"

  # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#home-info-mode
  homeInfoParams:
    title: Welcome!
    Content: I'm a tech person

  socialIcons:
    - name: twitter
      url: "https://twitter.com/zavocc"
    - name: mastodon
      url: "https://techhub.social/@zavocc"
    - name: discord
      url: "https://discord.com/users/1039885147761283113"
    - name: github
      url: "https://github.com/zavocc"
    - name: youtube
      url: "https://youtube.com/@marcuszavocc"
    
  # analytics:
    # google:
      # SiteVerificationTag: "XYZabC"

  # Show cover photos in posts view of the home page
  cover:
    hidden: false # Set to true to disable displaying cover photo in the home page posts (paginated)
    hiddenInList: true # https://github.com/adityatelange/hugo-PaperMod/discussions/631 ?
    hiddenInSingle: false # Set to true to disable displaying cover photo on your blog page

menu:
  main:
    - identifier: Posts
      name: Blogs
      url: /posts
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: Categories
      name: Categories
      url: /categories
      weight: 30
    - identifier: About
      name: About Me
      url: /about
      weight: 40

# https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# For code snippets display
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: catppuccin-frappe
    tabWidth: 4
